/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.98
 * Generated at: 2025-02-03 11:39:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class supplement_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>NutriPro Supplements Store</title>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Favicon -->\r\n");
      out.write("    <link rel=\"icon\" href=\"images/favicon.ico\" type=\"image/x-icon\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- Font Awesome for Icons -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- Bootstrap 5 -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <style>\r\n");
      out.write("        :root {\r\n");
      out.write("            --primary-color: #007bff;\r\n");
      out.write("            --secondary-color: #6c757d;\r\n");
      out.write("            --dark-bg: #121212;\r\n");
      out.write("            --card-bg: #1e1e1e;\r\n");
      out.write("            --text-light: #f4f4f4;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            background: linear-gradient(135deg, var(--dark-bg) 0%, #1a1a2e 100%);\r\n");
      out.write("            color: var(--text-light);\r\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .supplements-header {\r\n");
      out.write("            background: rgba(0,0,0,0.5);\r\n");
      out.write("            padding: 20px 0;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("            border-bottom: 2px solid var(--primary-color);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .item-card {\r\n");
      out.write("            transition: all 0.4s cubic-bezier(0.25, 0.46, 0.45, 0.94);\r\n");
      out.write("            border: none;\r\n");
      out.write("            background: var(--card-bg);\r\n");
      out.write("            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .item-card::after {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            bottom: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 4px;\r\n");
      out.write("            background: linear-gradient(to right, var(--primary-color), var(--secondary-color));\r\n");
      out.write("            transform: scaleX(0);\r\n");
      out.write("            transition: transform 0.4s ease-in-out;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .item-card:hover::after {\r\n");
      out.write("            transform: scaleX(1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .item-card:hover {\r\n");
      out.write("            transform: translateY(-10px);\r\n");
      out.write("            box-shadow: 0 12px 16px rgba(0, 0, 0, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .item-card img {\r\n");
      out.write("            height: 250px;\r\n");
      out.write("            object-fit: cover;\r\n");
      out.write("            transition: filter 0.4s ease, transform 0.4s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .item-card:hover img {\r\n");
      out.write("            filter: brightness(110%);\r\n");
      out.write("            transform: scale(1.05);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .product-info {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            padding: 10px 15px;\r\n");
      out.write("            background: rgba(0,0,0,0.1);\r\n");
      out.write("            border-top: 1px solid rgba(255,255,255,0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-title {\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            font-size: 1.1em;\r\n");
      out.write("            transition: color 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .item-card:hover .card-title {\r\n");
      out.write("            color: var(--primary-color);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .price-tag {\r\n");
      out.write("            font-size: 1.2em;\r\n");
      out.write("            color: #28a745;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-supplement {\r\n");
      out.write("            background: var(--primary-color);\r\n");
      out.write("            border: none;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-supplement:hover {\r\n");
      out.write("            background: #0056b3;\r\n");
      out.write("            transform: translateY(-3px);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .badge-id {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 15px;\r\n");
      out.write("            right: 15px;\r\n");
      out.write("            background: rgba(0,0,0,0.7);\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 5px 10px;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            font-size: 0.8em;\r\n");
      out.write("            z-index: 10;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Responsive Adjustments */\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            .item-card {\r\n");
      out.write("                margin-bottom: 20px;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("         .btn-back {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            left: 20px;\r\n");
      out.write("            top: 50%;\r\n");
      out.write("            transform: translateY(-50%);\r\n");
      out.write("            background: rgba(255,255,255,0.1);\r\n");
      out.write("            color: var(--text-light);\r\n");
      out.write("            border: 1px solid rgba(255,255,255,0.2);\r\n");
      out.write("            padding: 10px 15px;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-back:hover {\r\n");
      out.write("            background: rgba(255,255,255,0.2);\r\n");
      out.write("            color: var(--primary-color);\r\n");
      out.write("            transform: translateY(-50%) scale(1.05);\r\n");
      out.write("            box-shadow: 0 4px 8px rgba(0,0,0,0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .supplements-header {\r\n");
      out.write("            position: relative;\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("    <div class=\"container-fluid supplements-header text-center\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <h1 class=\"display-4\">\r\n");
      out.write("                <i class=\"fas fa-dumbbell me-2\"></i>NutriPro Supplements\r\n");
      out.write("            </h1>\r\n");
      out.write("            <p class=\"lead\">Elevate Your Fitness Journey</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row g-4\">\r\n");
      out.write("            ");
 
            String[][] supplements = {
                {"01", "Protein Powder", "Advanced muscle recovery formula", "images/protein1.jpg", "3999"},
                {"02", "Fish Oil", "Premium Omega-3 supplement", "images/f.jpg", "1499"},
                {"03", "Multivitamins", "Complete daily nutrition", "images/multi.jpg", "999"},
                {"04", "BCAA", "Muscle growth accelerator", "images/bc.jpg", "1299"},
                {"05", "Creatine", "Performance enhancement", "images/creatine.jpg", "989"},
                {"06", "Shilajit", "Natural energy booster", "images/shil.jpg", "599"},
                {"07", "Glutamine", "Recovery and immune support", "images/glut.jpg", "1299"},
                {"08", "ZMA", "Advanced mineral complex", "images/zma.jpg", "499"},
                {"09", "Mass Gainer", "Lean muscle development", "images/ga.jpg", "2999"},
                {"10", "Vitamin Complex", "Comprehensive nutritional support", "images/vitamin.jpg", "899"}
            };

            for (String[] supplement : supplements) {
            
      out.write("\r\n");
      out.write("            <div class=\"col-md-3 col-sm-6\">\r\n");
      out.write("                <div class=\"item-card h-100\">\r\n");
      out.write("                    <span class=\"badge-id\">");
      out.print( supplement[0] );
      out.write("</span>\r\n");
      out.write("                    <img src=\"");
      out.print( supplement[3] );
      out.write("\" class=\"card-img-top\" alt=\"");
      out.print( supplement[1] );
      out.write("\">\r\n");
      out.write("                    <div class=\"card-body text-center\">\r\n");
      out.write("                        <div class=\"product-info\">\r\n");
      out.write("                            <h5 class=\"card-title\">");
      out.print( supplement[1] );
      out.write("</h5>\r\n");
      out.write("                            <p class=\"price-tag\">₹");
      out.print( supplement[4] );
      out.write("</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <p class=\"card-text text-muted mt-2\">");
      out.print( supplement[2] );
      out.write("</p>\r\n");
      out.write("                        <button onclick=\"buySupplement('");
      out.print( supplement[0] );
      out.write("')\" \r\n");
      out.write("                                class=\"btn btn-supplement btn-primary w-100\">\r\n");
      out.write("                            <i class=\"fas fa-shopping-cart\"></i> Buy Now\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        function buySupplement(supplementId) {\r\n");
      out.write("            try {\r\n");
      out.write("                window.location.href = `buy?supplementId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${supplementId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`;\r\n");
      out.write("            } catch (error) {\r\n");
      out.write("                console.error('Purchase Error:', error);\r\n");
      out.write("                alert('Purchase failed. Please try again.');\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
