/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.98
 * Generated at: 2025-02-03 11:39:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class workout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Professional Workout Strategy</title>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Performance Optimization -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preload\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\" as=\"style\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- Google Fonts -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- Animate.css -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- Font Awesome -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\">\r\n");
      out.write("    \r\n");
      out.write("    <style>\r\n");
      out.write("      :root {\r\n");
      out.write("    --primary-color: #2c3e50;\r\n");
      out.write("    --secondary-color: #3498db;\r\n");
      out.write("    --accent-color: #2ecc71;\r\n");
      out.write("    --background-color: #ecf0f1;\r\n");
      out.write("    --text-color: #34495e;\r\n");
      out.write("    --transition-speed: 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("* {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    transition: all 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("    font-family: 'Poppins', sans-serif;\r\n");
      out.write("    background: linear-gradient(135deg, var(--background-color) 0%, #ffffff 100%);\r\n");
      out.write("    color: var(--text-color);\r\n");
      out.write("    line-height: 1.6;\r\n");
      out.write("    perspective: 1000px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".workout-container {\r\n");
      out.write("    max-width: 1200px;\r\n");
      out.write("    margin: 40px auto;\r\n");
      out.write("    padding: 30px;\r\n");
      out.write("    background: white;\r\n");
      out.write("    border-radius: 15px;\r\n");
      out.write("    box-shadow: 0 20px 50px rgba(0,0,0,0.1);\r\n");
      out.write("    transform-style: preserve-3d;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".workout-header {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    margin-bottom: 40px;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    transform: translateZ(50px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".workout-header h1 {\r\n");
      out.write("    color: var(--accent-color);\r\n");
      out.write("    font-size: 2.5rem;\r\n");
      out.write("    font-weight: 600;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".workout-header h1::after {\r\n");
      out.write("    content: '';\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    bottom: -10px;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 4px;\r\n");
      out.write("    background: linear-gradient(to right, var(--primary-color), var(--secondary-color));\r\n");
      out.write("    transform: scaleX(0);\r\n");
      out.write("    transition: transform 0.5s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".workout-header:hover h1::after {\r\n");
      out.write("    transform: scaleX(1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-back {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    top: 50%;\r\n");
      out.write("    transform: translateY(-50%);\r\n");
      out.write("    background: rgba(0,0,0,0.05);\r\n");
      out.write("    color: var(--text-color);\r\n");
      out.write("    padding: 10px 15px;\r\n");
      out.write("    border-radius: 8px;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    transition: all 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-back:hover {\r\n");
      out.write("    background: rgba(0,0,0,0.1);\r\n");
      out.write("    transform: translateY(-50%) translateX(-5px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".workout-strategy-grid {\r\n");
      out.write("    display: grid;\r\n");
      out.write("    grid-template-columns: repeat(3, 1fr);\r\n");
      out.write("    gap: 30px;\r\n");
      out.write("    transform-style: preserve-3d;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".workout-card {\r\n");
      out.write("    background: white;\r\n");
      out.write("    border-radius: 15px;\r\n");
      out.write("    padding: 30px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    box-shadow: 0 15px 40px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    transition: all 0.4s cubic-bezier(0.175, 0.885, 0.32, 1.275);\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    transform-style: preserve-3d;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".workout-card::before {\r\n");
      out.write("    content: '';\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    left: -100%;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 4px;\r\n");
      out.write("    background: linear-gradient(to right, transparent, var(--accent-color));\r\n");
      out.write("    transition: all 0.5s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".workout-card:hover::before {\r\n");
      out.write("    left: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".workout-card:hover {\r\n");
      out.write("    transform: translateY(-15px) scale(1.05);\r\n");
      out.write("    box-shadow: 0 20px 50px rgba(0, 0, 0, 0.2);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".workout-card-icon {\r\n");
      out.write("    font-size: 60px;\r\n");
      out.write("    color: var(--secondary-color);\r\n");
      out.write("    margin-bottom: 20px;\r\n");
      out.write("    transition: all 0.4s cubic-bezier(0.68, -0.55, 0.265, 1.55);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".workout-card:hover .workout-card-icon {\r\n");
      out.write("    transform: translateY(-10px) scale(1.1);\r\n");
      out.write("    color: var(--accent-color);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".workout-card-title {\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    font-weight: 600;\r\n");
      out.write("    margin-bottom: 15px;\r\n");
      out.write("    color: var(--text-color);\r\n");
      out.write("    transition: color 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".workout-card:hover .workout-card-title {\r\n");
      out.write("    color: var(--secondary-color);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".workout-card-description {\r\n");
      out.write("    color: #6c757d;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    line-height: 1.6;\r\n");
      out.write("    transition: color 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".workout-card:hover .workout-card-description {\r\n");
      out.write("    color: var(--primary-color);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media (max-width: 768px) {\r\n");
      out.write("    .workout-strategy-grid {\r\n");
      out.write("        grid-template-columns: 1fr;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Additional Subtle Animations */\r\n");
      out.write("@keyframes subtleFloat {\r\n");
      out.write("    0% {\r\n");
      out.write("        transform: translateY(0);\r\n");
      out.write("    }\r\n");
      out.write("    50% {\r\n");
      out.write("        transform: translateY(-5px);\r\n");
      out.write("    }\r\n");
      out.write("    100% {\r\n");
      out.write("        transform: translateY(0);\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".workout-card {\r\n");
      out.write("    animation: subtleFloat 4s ease-in-out infinite;\r\n");
      out.write("}\r\n");
      out.write("      \r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"workout-container animate__animated animate__fadeIn\">\r\n");
      out.write("        <div class=\"workout-header\">\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myProfile\" class=\"btn-back\">\r\n");
      out.write("                <i class=\"fas fa-arrow-left\"></i> Back to Profile\r\n");
      out.write("            </a>\r\n");
      out.write("            <h1>Professional Workout Strategy</h1>\r\n");
      out.write("            <p>Select your personalized fitness approach</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"workout-strategy-grid\">\r\n");
      out.write("            <!-- Strength Training Card -->\r\n");
      out.write("            <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/strength\" method=\"POST\">\r\n");
      out.write("                <div class=\"workout-card animate__animated animate__zoomIn\" onclick=\"this.closest('form').submit()\">\r\n");
      out.write("                    <div class=\"workout-card-icon\">\r\n");
      out.write("                        <i class=\"fas fa-dumbbell\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"workout-card-title\">Strength Training</div>\r\n");
      out.write("                    <div class=\"workout-card-description\">\r\n");
      out.write("                        Develop muscle strength, enhance power, and improve overall body composition through targeted resistance exercises.\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <input type=\"hidden\" name=\"workoutType\" value=\"strengthTraining\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("\r\n");
      out.write("            <!-- Weight Loss Card -->\r\n");
      out.write("            <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/weightloss\" method=\"POST\">\r\n");
      out.write("                <div class=\"workout-card animate__animated animate__zoomIn\" onclick=\"this.closest('form').submit()\">\r\n");
      out.write("                    <div class=\"workout-card-icon\">\r\n");
      out.write("                        <i class=\"fas fa-weight\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"workout-card-title\">Weight Loss Training</div>\r\n");
      out.write("                    <div class=\"workout-card-description\">\r\n");
      out.write("                        Optimize metabolism, burn calories, and achieve sustainable fat loss through high-intensity and strategic workouts.\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <input type=\"hidden\" name=\"workoutType\" value=\"weightLoss\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("\r\n");
      out.write("            <!-- Flexibility Card -->\r\n");
      out.write("            <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/flex\" method=\"POST\">\r\n");
      out.write("                <div class=\"workout-card animate__animated animate__zoomIn\" onclick=\"this.closest('form').submit()\">\r\n");
      out.write("                    <div class=\"workout-card-icon\">\r\n");
      out.write("                        <i class=\"fas fa-wind\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"workout-card-title\">Flexibility Traning</div>\r\n");
      out.write("                    <div class=\"workout-card-description\">\r\n");
      out.write("                        Improve mobility, reduce injury risk, and enhance overall physical performance through comprehensive stretching routines.\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <input type=\"hidden\" name=\"workoutType\" value=\"flexibility\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
